let version = "v0.1-37-geef013d"
let compile_time = "11/10/2014 14:20:49 UTC"
let platform = "Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386"
let ocaml_version = "4.01.0"
let synopsis = "netlist"
let description = "Executable joule\nPath:           src\nMainIs:         netlist.ml\nBuildDepends:   core,\n                sexplib,\n                sexplib.syntax,\n                comparelib,\n                comparelib.syntax,\n                ocamlgraph,\n                threads,\n                ctypes,\n                ctypes.foreign\nCompiledObject: best\nByteOpt:        -g\n\nTest netlist\nCommand: ./scripts/run_all_tests.pl joule.native my myerr; ./scripts/compare_results.pl ref my referr myerr\n\nPostCleanCommand:"
